### ISSUE TITLE
wait for tag being detected by code.dlang.org before creating the PR

### ISSUE THREAD

**Issue by ghost** [skl131313/somebot#1]
This problem happened yesterday. It takes up to 1 hour max, often less.

**Comment by skl131313** [comment]
I think creating the PR right away should stay, so that someone else doesn't end up creating a duplicate one, thinking it isn't working. Opening and closing the PR after an hour or after waiting for the tag to be detected could work. Would need to do some checks to make sure the PR is still open and hasn't merged yet and stuff like that.

**Comment by wilzbach** [comment]
We could also add some logic to restart the Travis builds.
I do something similar for the dlang tour:

https://github.com/dlang-tour/bot/blob/master/source/travis.d

E.g.: cron every hour for all open PRs of the bot, get their Travis CI builds and restart if failing.

**Comment by skl131313** [comment]
Yah would also need to do that for appveyor though, so I figured opening and closing might be easier. Especially if another CI gets added. If only github had some way to notify CIs to restart the build, rather than opening and closing a PR.

**Comment by ghost** [comment]
You could create threads for each repository. Thread checks every 5 minutes if dlang.org has updated.
Allow up to 80 checks. If after 80 checks code.dlang.org not updated then create the PRs anyway and let one of us close / reopen manually.

**Comment by ghost** [comment]
Well no thread needed actually. Just a loop with wait, all the PRs can be created at the same time.
